CREATE SCHEMA IF NOT EXISTS whatsapp;
CREATE EXTENSION IF NOT EXISTS "uuid-osp" SCHEMA public;
CREATE TYPE whatsapp.connection_state AS ENUM ('pending','connecting','open','close','disconnected');
CREATE TYPE whatsapp.message_direction AS ENUM ('in','out');
CREATE TYPE whatsapp.content_type AS ENUM ('text','image','video','audio','document','sticker','location','contact','reaction','gif','voice_note','unknown');
CREATE TABLE whatsapp.devices (id UUID PRIMARY KEY DEFAULT public.uuid_generate_v4(),user_id UUID NOT NULL,device_name VARCHAR(100) NOT NULL,instance_name VARCHAR(100) NOT NULL,phone_number VARCHAR(20) DEFAULT '',avatar_url TEXT DEFAULT '',state whatsapp.connection_state DEFAULT 'pending',evo_instance_id VARCHAR(100) DEFAULT '',qr_code TEXT DEFAULT '',qr_updated_at TIMESTAMPTZ DEFAULT NULL,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW(),CONSTRAINT devices_user_instance_uk UNIQUE(user_id,device_name));
CREATE TABLE whatsapp.conversations (id UUID PRIMARY KEY DEFAULT public.uuid_generate_v4(),device_id UUID NOT NULL REFERENCES whatsapp.devices(id) ON DELETE CASCADE,jid VARCHAR(255) NOT NULL,name VARCHAR(255) DEFAULT '',pushname VARCHAR(255) DEFAULT '',avatar_url TEXT DEFAULT '',is_group BOOLEAN DEFAULT FALSE,is_archived BOOLEAN DEFAULT FALSE,is_muted BOOLEAN DEFAULT FALSE,is_pinned BOOLEAN DEFAULT FALSE,unread_count INTEGER DEFAULT 0 CHECK(unread_count>=0),last_message_id UUID DEFAULT NULL,last_message_at TIMESTAMPTZ DEFAULT NULL,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW(),CONSTRAINT conversations_device_jid_uk UNIQUE(device_id,jid));
CREATE TABLE whatsapp.messages (id UUID PRIMARY KEY DEFAULT public.uuid_generate_v4(),device_id UUID NOT NULL REFERENCES whatsapp.devices(id) ON DELETE CASCADE,conversation_id UUID NOT NULL REFERENCES whatsapp.conversations(id) ON DELETE CASCADE,message_id VARCHAR(255) NOT NULL,evo_id VARCHAR(255) DEFAULT '',direction whatsapp.message_direction NOT NULL,content TEXT DEFAULT '',content_type whatsapp.content_type DEFAULT 'text',media_url TEXT DEFAULT '',media_mime VARCHAR(100) DEFAULT '',media_size BIGINT DEFAULT 0,from_jid VARCHAR(255) DEFAULT '',to_jid VARCHAR(255) DEFAULT '',from_me BOOLEAN DEFAULT FALSE,from_bot BOOLEAN DEFAULT FALSE,timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),expires_at TIMESTAMPTZ DEFAULT NULL,is_deleted BOOLEAN DEFAULT FALSE,is_forwarded BOOLEAN DEFAULT FALSE,reply_to_id UUID DEFAULT NULL REFERENCES whatsapp.messages(id) ON DELETE SET NULL,reaction VARCHAR(100) DEFAULT '',reactions JSONB DEFAULT '[]'::JSONB,created_at TIMESTAMPTZ DEFAULT NOW(),CONSTRAINT messages_device_message_uk UNIQUE(device_id,message_id));
CREATE TABLE whatsapp.contacts (id UUID PRIMARY KEY DEFAULT public.uuid_generate_v4(),device_id UUID NOT NULL REFERENCES whatsapp.devices(id) ON DELETE CASCADE,jid VARCHAR(255) NOT NULL,name VARCHAR(255) DEFAULT '',pushname VARCHAR(255) DEFAULT '',avatar_url TEXT DEFAULT '',about TEXT DEFAULT '',isblocked BOOLEAN DEFAULT FALSE,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW(),CONSTRAINT contacts_device_jid_uk UNIQUE(device_id,jid));
CREATE INDEX idx_devices_user_id ON whatsapp.devices(user_id);
CREATE INDEX idx_devices_state ON whatsapp.devices(state);
CREATE INDEX idx_conv_device_id ON whatsapp.conversations(device_id);
CREATE INDEX idx_conv_last_msg ON whatsapp.conversations(last_message_at DESC NULLS LAST);
CREATE INDEX idx_conv_unread ON whatsapp.conversations(device_id,unread_count DESC) WHERE unread_count>0;
CREATE INDEX idx_conv_jid ON whatsapp.conversations(device_id,jid);
CREATE INDEX idx_msg_device_id ON whatsapp.messages(device_id);
CREATE INDEX idx_msg_conv_id ON whatsapp.messages(conversation_id);
CREATE INDEX idx_msg_conv_time ON whatsapp.messages(conversation_id,timestamp DESC);
CREATE INDEX idx_msg_from_jid ON whatsapp.messages(from_jid);
CREATE INDEX idx_msg_timestamp ON whatsapp.messages(timestamp DESC);
CREATE INDEX idx_msg_evo_id ON whatsapp.messages(device_id,evo_id) WHERE evo_id<>'';
CREATE INDEX idx_contacts_device_id ON whatsapp.contacts(device_id);
CREATE OR REPLACE FUNCTION whatsapp.set_updated_at() RETURNS TRIGGER AS $$BEGIN NEW.updated_at=NOW(); RETURN NEW; END;$$ LANGUAGE plpgsql;
CREATE TRIGGER devices_updated_at BEFORE UPDATE ON whatsapp.devices FOR EACH ROW EXECUTE PROCEDURE whatsapp.set_updated_at();
CREATE TRIGGER conversations_updated_at BEFORE UPDATE ON whatsapp.conversations FOR EACH ROW EXECUTE PROCEDURE whatsapp.set_updated_at();
CREATE TRIGGER contacts_updated_at BEFORE UPDATE ON whatsapp.contacts FOR EACH ROW EXECUTE PROCEDURE whatsapp.set_updated_at();
CREATE OR REPLACE FUNCTION whatsapp.update_conv_last_msg() RETURNS TRIGGER AS $$BEGIN UPDATE whatsapp.conversations SET last_message_id=NEW.id,last_message_at=NEW.timestamp WHERE id=NEW.conversation_id AND (last_message_at IS NULL OR last_message_at<NEW.timestamp); RETURN NEW; END;$$ LANGUAGE plpgsql;
CREATE TRIGGER msg_update_conv AFTER INSERT ON whatsapp.messages FOR EACH ROW EXECUTE PROCEDURE whatsapp.update_conv_last_msg();
CREATE OR REPLACE FUNCTION whatsapp.inc_unread() RETURNS TRIGGER AS $$BEGIN IF NEW.direction='in' AND NEW.from_me=FALSE THEN UPDATE whatsapp.conversations SET unread_count=unread_count+1 WHERE id=NEW.conversation_id; END IF; RETURN NEW; END;$$ LANGUAGE plpgsql;
CREATE TRIGGER msg_inc_unread AFTER INSERT ON whatsapp.messages FOR EACH ROW EXECUTE PROCEDURE whatsapp.inc_unread();
GRANT USAGE ON SCHEMA whatsapp TO public;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA whatsapp TO public;
GRANT USAGE ON SCHEMA whatsapp TO kero;